version: '3.7'

services:
  php:
    build: .docker/php
    volumes:
      - .:/app
      - ~/.composer:/root/.composer
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=9003 start_with_request=yes