version: '3'

services:
  web:
    build: ./docker/nginx/
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    links:
      - php
  php:
    build: ./docker/php
    env_file:
      - .env
    volumes:
      - .:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
  composer:
    image: "composer"
    volumes:
      - ./:/app
    command: install
